name: testCluster
spec:
  listeners:
  - name: listerner1
    address: 0.0.0.0
    port: 9000
    routes:
    - name:
      prefix: /
      hostRewrite: www.envoyproxy.io
      cluster: envoy-web
  clusters:
  - name: echo-server-1
    endpoints:
    - address: 172.22.0.2
      port: 8080
  - name: echo-server-2
    endpoints:
    - address: 172.22.0.4
      port: 8080
  - name: echo-server-3
    endpoints:
    - address: 172.22.0.7
      port: 8080
  - name: envoy-web
    isHTTPS: true
    endpoints:
    - address: 206.189.73.52
      port: 443
